import './globals.css'

import '@fontsource/ibm-plex-sans';
import '@fontsource/roboto';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full'>
      <body className='bg-primary_main h-full'>{children}</body>
    </html>
  )
}
